data<-read.csv("E:\\DATA SETS\\titanic.csv")
library(caTools)
S1=sample.split(data,SplitRatio=.8)
train=subset(data,S1==TRUE)
test=subset(data,S1==FALSE)
library(party)
model2=ctree(Survived~Pclass+Age,data=train)
#print(model2)
plot(model2)
p2=predict(model2,test)
table2=table(p2,test$Survived)
print(table2)      
#print(p2[1:5])