data<-read.csv("E:\\DATA SETS\\titanic.csv")
library(caTools)
S3=sample.split(data,SplitRatio=.8)
train=subset(data,S3==TRUE)
test=subset(data,S3==FALSE)
library(e1071)
model4=svm(Survived~Pclass+Age,data=train)
#print(model2)
plot(model4)
p4=predict(model4,test)
table4=table(p4,test$Survived)
print(table4)                